# Binance 适配器开发环境配置
# 此文件用于本地开发和测试

# WebSocket 端点配置
wsEndpoint: 'wss://stream.binance.com:9443'
restEndpoint: 'https://api.binance.com'

# 环境设置
environment: development

# 连接配置
connection:
  maxConnections: 2
  maxStreamsPerConnection: 50
  heartbeatInterval: 20000
  pingTimeout: 25000
  connectionTimeout: 15000

# 重试配置
retry:
  maxRetries: 5
  initialDelay: 1000
  maxDelay: 10000
  backoffMultiplier: 2.0
  jitter: true

# 订阅配置
subscriptions:
  # 开发环境只订阅少量符号
  defaultSymbols:
    - BTCUSDT
    - ETHUSDT
  
  supportedDataTypes:
    - trade
    - kline_1m
    - kline_5m
    - ticker
  
  # 批量订阅设置
  batchSubscription:
    enabled: true
    batchSize: 10
    batchInterval: 1000
  
  # 订阅管理
  management:
    autoResubscribe: true
    subscriptionTimeout: 10000
    maxConcurrentSubscriptions: 100

# 日志配置
logging:
  level: debug
  format: text
  structured: false

# 监控配置
monitoring:
  prometheus:
    enabled: true
    port: 9091
    path: /metrics
  healthCheck:
    interval: 30000
    timeout: 5000

# Google Cloud 配置 (开发环境使用模拟器)
googleCloud:
  projectId: pixiu-trading-dev
  pubsub:
    enabled: true
    # 使用本地 Pub/Sub 模拟器
    emulatorHost: localhost:8085
    topicPrefix: dev-market
    publishSettings:
      enableMessageOrdering: false
      batchSettings:
        maxMessages: 100
        maxBytes: 1048576  # 1MB
        maxLatency: 100
      retrySettings:
        maxRetries: 3
        initialRetryDelay: 100
        maxRetryDelay: 1000
  monitoring:
    enabled: false
    metricPrefix: dev/binance/adapter