# Binance 适配器测试环境配置
# 此文件用于自动化测试

# WebSocket 端点配置 (使用测试网)
wsEndpoint: 'wss://testnet.binance.vision/ws'
restEndpoint: 'https://testnet.binance.vision/api'

# 环境设置
environment: testing

# 连接配置 (测试环境使用最小配置)
connection:
  maxConnections: 1
  maxStreamsPerConnection: 10
  heartbeatInterval: 15000
  pingTimeout: 20000
  connectionTimeout: 10000

# 重试配置 (测试环境快速失败)
retry:
  maxRetries: 3
  initialDelay: 500
  maxDelay: 5000
  backoffMultiplier: 2.0
  jitter: false

# 订阅配置
subscriptions:
  # 测试环境只订阅一个符号
  defaultSymbols:
    - BTCUSDT
  
  supportedDataTypes:
    - trade
    - kline_1m
    - ticker
  
  # 批量订阅设置 (测试环境禁用批量)
  batchSubscription:
    enabled: false
    batchSize: 5
    batchInterval: 2000
  
  # 订阅管理
  management:
    autoResubscribe: false
    subscriptionTimeout: 5000
    maxConcurrentSubscriptions: 10

# 日志配置 (测试环境详细日志)
logging:
  level: debug
  format: text
  structured: false

# 监控配置 (测试环境禁用监控)
monitoring:
  prometheus:
    enabled: false
    port: 0
    path: /metrics
  healthCheck:
    interval: 10000
    timeout: 2000