version: '3.8'

# Minimal development environment - only essential services
services:
  # Message Bus
  kafka:
    image: bitnami/kafka:3.5
    container_name: kafka-dev
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - kafka-data:/bitnami/kafka

  # Databases
  postgres:
    image: postgres:15-alpine
    container_name: postgres-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: trading
      POSTGRES_PASSWORD: trading123
      POSTGRES_DB: trading_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: timescaledb-dev
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: tsdb
      POSTGRES_PASSWORD: tsdb123
      POSTGRES_DB: market_data
    volumes:
      - timescale-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis-dev
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

volumes:
  kafka-data:
  postgres-data:
  timescale-data:
  redis-data:

networks:
  default:
    name: pixiu-dev-network