version: '3.8'

# Minimal development environment - only essential services
services:
  # Message Bus - Google Cloud Pub/Sub Emulator
  pubsub-emulator:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    container_name: pubsub-emulator-dev
    ports:
      - "8085:8085"
    command: >
      bash -c "gcloud beta emulators pubsub start --host-port=0.0.0.0:8085 --verbosity=info"
    environment:
      - PUBSUB_EMULATOR_HOST=localhost:8085
      - GOOGLE_CLOUD_PROJECT=pixiu-trading-dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Databases
  postgres:
    image: postgres:15-alpine
    container_name: postgres-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: trading
      POSTGRES_PASSWORD: trading123
      POSTGRES_DB: trading_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: timescaledb-dev
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: tsdb
      POSTGRES_PASSWORD: tsdb123
      POSTGRES_DB: market_data
    volumes:
      - timescale-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis-dev
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  timescale-data:
  redis-data:

networks:
  default:
    name: pixiu-dev-network