# Exchange Collector 开发环境配置
name: exchange-collector
version: 1.0.0
environment: development

server:
  port: 8080
  host: 0.0.0.0
  enableCors: true

# 适配器配置 - 通用格式
adapters:
  binance:
    config:
      enabled: true
      endpoints:
        ws: wss://stream.binance.com:9443/ws
        rest: https://api.binance.com/api
      connection:
        timeout: 10000
        maxRetries: 3
        retryInterval: 5000
        heartbeatInterval: 30000
    subscription:
      symbols:
        - BTCUSDT
        - ETHUSDT
      dataTypes:
        - trade
        - ticker
        - kline_1m
      enableAllTickers: false
      customParams: {}
    extensions:
      testnet: false
      enableCompression: true
      enableCombinedStream: true
      maxStreamCount: 1024

# Google Cloud Pub/Sub 配置
pubsub:
  projectId: pixiu-trading-dev
  useEmulator: false
  # emulatorHost: localhost:8085  # 注释掉模拟器
  topicPrefix: market-data
  publishSettings:
    enableBatching: true
    batchSize: 100
    batchTimeout: 1000
    enableMessageOrdering: false
    retrySettings:
      maxRetries: 3
      initialRetryDelay: 1000
      maxRetryDelay: 60000

# 监控配置
monitoring:
  enableMetrics: true
  enableHealthCheck: true
  metricsInterval: 30000
  healthCheckInterval: 30000
  # 统计报告配置
  statsReportInterval: 30000   # 统计报告间隔 (ms)
  verboseStats: false          # 详细统计模式
  showZeroValues: false        # 显示零值
  prometheus:
    enabled: true
    port: 9090
    path: /metrics

# 日志配置
logging:
  level: debug
  format: json
  output: console