# Exchange Collector开发环境配置

name: exchange-collector
version: 1.0.0
environment: development

server:
  port: 8080
  host: '0.0.0.0'
  enableCors: true

adapters:
  binance:
    enabled: true
    config:
      endpoints:
        ws: 'wss://stream.binance.com:9443/ws'
        rest: 'https://api.binance.com/api'
      connection:
        timeout: 10000
        maxRetries: 3
        retryInterval: 5000
        heartbeatInterval: 30000
      binance:
        testnet: false
        enableCompression: true
    subscription:
      symbols:
        - 'BTC/USDT'
        - 'ETH/USDT'
        - 'ADA/USDT'
        - 'DOT/USDT'
      dataTypes:
        - 'trade'
        - 'ticker'
        - 'kline_1m'
      enableAllTickers: false

pubsub:
  projectId: 'pixiu-trading-dev'
  useEmulator: true
  emulatorHost: 'localhost:8085'
  topicPrefix: 'market-data'
  publishSettings:
    enableBatching: true
    batchSize: 100
    batchTimeout: 1000
    enableMessageOrdering: false
    retrySettings:
      maxRetries: 3
      initialRetryDelay: 1000
      maxRetryDelay: 60000

monitoring:
  enableMetrics: true
  enableHealthCheck: true
  metricsInterval: 30000
  healthCheckInterval: 30000
  prometheus:
    enabled: true
    port: 9090
    path: '/metrics'

logging:
  level: 'debug'
  format: 'json'
  output: 'console'